FORMAT: 1A
HOST: http://ec2-54-218-59-119.us-west-2.compute.amazonaws.com/api/v1

# Findoo

Registration is a simple API allowing user to signup

## Signup [/signup/]

### Create an user [POST]

+ Request (application/json)

        {
            "email" : "johndoe@mail.com",
            "password" : "letmein",
            "verifyEmailUrl": "http://localhost:3000/#/verify-email"
        }

+ Response 200 (application/json)

        
        {
            "key": "f982efd57ebc08ca24722022da2a67b64f2d4a3d"
        }
        
## Login [/login/]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }